### ISSUE TITLE
the content beside the logo on the homepage is shifted rightwards

### ISSUE THREAD

**Issue by gunjjoshi** [CSYClubIIITK/club-page#3]
The name of the club and the line below it are slightly towards right. Bring them a bit towards left, nearer to the logo.
You can find it in the index.js file.

![image](https://github.com/CSYClubIIITK/club-page/assets/67432819/67c9b9eb-79c8-4256-b243-b20e0dd8f554)

**Comment by Kinjal2004** [comment]
I want to work on this issue

**Comment by CSYClubIIITK** [comment]
Sure, please start working on it

**Comment by Kinjal2004** [comment]
<img width="1159" alt="Screenshot 2023-10-26 at 11 49 14 PM" src="https://github.com/CSYClubIIITK/club-page/assets/112677948/a84028f0-64e0-4838-96c1-49a028296089">

These are the changes were made in the code which includes adding two paddings which are width based and divided the screen in 4.5:5 ratio for a better spacing 

The page currently looks like this:

<img width="1426" alt="Screenshot 2023-10-26 at 11 47 43 PM" src="https://github.com/CSYClubIIITK/club-page/assets/112677948/904e77c3-4327-4315-a2ec-768505b38579">

Please inform if further changes are required.
